arch:
  - arm64
os:
  - linux
services:
  - docker
before_install:
  - docker build -t toyangdon/dockerize:latest .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push toyangdon/dockerize:latest
 
